/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;
import java.awt.JobAttributes; 
public class dlgCotizacion extends javax.swing.JDialog {
    /**
     * Creates new form dlgCotizacion
     */
    public dlgCotizacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFolio = new javax.swing.JTextField();
        txtDescripcion = new javax.swing.JTextField();
        txtPagoI = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        cmbPlazo = new javax.swing.JComboBox<String>();
        btnNuevo = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        txtCalcularPaI = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCalcularPaM = new javax.swing.JTextField();
        btnCerrar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        txtCalcularTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Folio");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 14, 28, 15);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Descripcion");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 40, 69, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Precio");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 67, 37, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Por. Pago Inicial");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(49, 94, 120, 15);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Plazo");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(49, 120, 32, 15);

        txtFolio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtFolio.setForeground(new java.awt.Color(0, 0, 153));
        txtFolio.setEnabled(false);
        txtFolio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFolioActionPerformed(evt);
            }
        });
        getContentPane().add(txtFolio);
        txtFolio.setBounds(168, 11, 66, 21);

        txtDescripcion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(0, 0, 153));
        txtDescripcion.setEnabled(false);
        getContentPane().add(txtDescripcion);
        txtDescripcion.setBounds(168, 40, 66, 21);

        txtPagoI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPagoI.setForeground(new java.awt.Color(0, 0, 153));
        txtPagoI.setEnabled(false);
        getContentPane().add(txtPagoI);
        txtPagoI.setBounds(168, 94, 66, 20);

        txtPrecio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(0, 0, 153));
        txtPrecio.setEnabled(false);
        getContentPane().add(txtPrecio);
        txtPrecio.setBounds(168, 67, 66, 21);

        cmbPlazo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "12", "24", "36", "48" }));
        cmbPlazo.setEnabled(false);
        cmbPlazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPlazoActionPerformed(evt);
            }
        });
        getContentPane().add(cmbPlazo);
        cmbPlazo.setBounds(168, 120, 90, 20);

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });
        getContentPane().add(btnNuevo);
        btnNuevo.setBounds(290, 10, 90, 23);

        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(290, 50, 90, 23);

        btnMostrar.setText("Mostrar");
        btnMostrar.setEnabled(false);
        getContentPane().add(btnMostrar);
        btnMostrar.setBounds(290, 90, 90, 23);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Total Final");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 70, 62, 15);

        btnLimpiar.setText("Limpiar");
        btnLimpiar.setEnabled(false);
        jPanel1.add(btnLimpiar);
        btnLimpiar.setBounds(260, 30, 90, 23);

        txtCalcularPaI.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCalcularPaI.setForeground(new java.awt.Color(255, 255, 255));
        txtCalcularPaI.setToolTipText("");
        txtCalcularPaI.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCalcularPaI.setEnabled(false);
        jPanel1.add(txtCalcularPaI);
        txtCalcularPaI.setBounds(140, 40, 66, 21);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Pago Inicial");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 40, 70, 15);

        txtCalcularPaM.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCalcularPaM.setForeground(new java.awt.Color(255, 255, 255));
        txtCalcularPaM.setToolTipText("");
        txtCalcularPaM.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCalcularPaM.setEnabled(false);
        jPanel1.add(txtCalcularPaM);
        txtCalcularPaM.setBounds(140, 100, 66, 21);

        btnCerrar.setText("Cerrar");
        jPanel1.add(btnCerrar);
        btnCerrar.setBounds(260, 110, 90, 23);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Pago Mensual");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 100, 85, 15);

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        jPanel1.add(btnCancelar);
        btnCancelar.setBounds(260, 70, 90, 23);

        txtCalcularTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtCalcularTotal.setForeground(new java.awt.Color(255, 255, 255));
        txtCalcularTotal.setToolTipText("");
        txtCalcularTotal.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCalcularTotal.setEnabled(false);
        jPanel1.add(txtCalcularTotal);
        txtCalcularTotal.setBounds(140, 70, 66, 21);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 180, 370, 160);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFolioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFolioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFolioActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void cmbPlazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPlazoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPlazoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgCotizacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() { 
                dlgCotizacion dialog = new dlgCotizacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnCerrar;
    public javax.swing.JButton btnGuardar;
    public javax.swing.JButton btnLimpiar;
    public javax.swing.JButton btnMostrar;
    public javax.swing.JButton btnNuevo;
    public javax.swing.JComboBox<String> cmbPlazo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField txtCalcularPaI;
    public javax.swing.JTextField txtCalcularPaM;
    public javax.swing.JTextField txtCalcularTotal;
    public javax.swing.JTextField txtDescripcion;
    public javax.swing.JTextField txtFolio;
    public javax.swing.JTextField txtPagoI;
    public javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
